import "~/styles/globals.css";

import { cx } from "cva";
import type { Metadata } from "next";
import { ModeSwitcher } from "~/components/mode-switcher";
import { Separator } from "~/components/ui/separator/separator";
import { fonts } from "~/config/fonts";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cx(fonts)}>
      <body>
        <Providers>
          <header className="sticky inset-x-0 top-0 isolate z-10 flex shrink-0 items-center gap-2 border-b bg-background">
            <div className="flex h-14 w-full items-center gap-2 px-4">
              {/* <SidebarTrigger className="-ml-1.5" /> */}
              <Separator
                orientation="vertical"
                className="mr-2 orientation-vertical:h-4"
              />
              {/* <NavHeader /> */}
              <div className="ml-auto flex items-center gap-2">
                {/* <ThemeSelector /> */}
                <ModeSwitcher />
              </div>
            </div>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
