import "~/styles/globals.css";

import { cx } from "cva";
import type { Metadata } from "next";
import { fonts } from "~/config/fonts";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={cx(fonts)}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
